version: '3'

services:
  bms-auth:
    container_name: bms-auth
    build:
      context: ./../bms-auth
      dockerfile: Dockerfile
    volumes:
      - ./../bms-auth:/app
      - /app/node_module
    ports:
      - 5001:5001
    env_file:
      - ./../bms-auth/.env

  bms-org:
    container_name: bms-org
    build:
      context: ./../bms-org
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    volumes:
      - ./../bms-org:/app
    env_file:
      - ./../bms-org/.env

  bms-core:
    container_name: bms-core
    build: .
    volumes:
      - ./nginx.conf:/etc/nginx/nginx/conf
    ports:
      - 80:80
    depends_on:
      - bms-auth
      - bms-org
