version: '3'

services:
  bms-auth:
    container_name: bms-auth
    build: 
      context: ./bms-auth
      dockerfile: dockerfile.dev
    volumes:
      - ./bms-auth:/app
      - /app/node_modules
    ports:
      - 5001:5001
    env_file:
      - ./bms-auth/.env
    depends_on:
      - bms-db
      - bms-mq
    command: ["npm","run","dev"]

  bms-mq:
    container_name: bms-mq
    image: rabbitmq:3.12-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 5s
      retries: 3
      
  bms-db:
    container_name: bms-db
    image: postgres:16-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  # nginx:
  #   container_name: nginx
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./nginx.dev.conf:/etc/nginx/nginx/conf
  #   ports:
  #     - 80:80
