version: '3'

services:
  nginx:
    container_name: nginx
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx/conf
    ports:
      - 80:80
